### ISSUE TITLE
I believe that 2 of your examples are switched in relation to where they should be in the tutorial

### ISSUE THREAD

**Issue by Dennis-Petre** [zairahira/read-files-python#2]
in the example of opening a file it looks like the example is switched with the one that is dealing with the extra line space

**Comment by zairahira** [comment]
Hi, thank you for raising the issue. Can you mention the line number and the text that should be replaced?

**Comment by Dennis-Petre** [comment]
I think lines 436 and 442 need to be switched to make examples line up as intended.

**Comment by Dennis-Petre** [comment]
Here is what I am seeing
The example and the output are not matching in these two places
![image](https://user-images.githubusercontent.com/64926184/176930513-6ed9a5cd-bf8b-4c40-9248-f193d31ba67a.png)
![image](https://user-images.githubusercontent.com/64926184/176930763-746d7129-e766-43cb-806c-69d56c294f29.png)

**Comment by zairahira** [comment]
Thank you for bringing this to my attention. I have updated the code blocks and their respective outputs. 👍 
See the [updated article](https://www.freecodecamp.org/news/how-to-read-files-in-python/).
